### ISSUE TITLE
add ping routine cause panic

### ISSUE THREAD

**Issue by lkzz** [go-mysql-org/go-mysql#102]
I add a new routine to check connection like this:

![image](https://cloud.githubusercontent.com/assets/5388526/20668403/b1944438-b5a9-11e6-914b-db435a0ace65.png)

panic info:

2016/11/28 20:19:02 binlogsyncer.go:514: [error] invalid sequence 1 != 2
panic: runtime error: slice bounds out of range

goroutine 54 [running]:
panic(0x3ce180, 0xc42000c130)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
bufio.(*Reader).Read(0xc4211fe7e0, 0xc4204bc394, 0x4, 0x4, 0x4, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:216 +0x2a8
io.ReadAtLeast(0x611c40, 0xc4211fe7e0, 0xc4204bc394, 0x4, 0x4, 0x4, 0x3b4200, 0x1, 0xc4204bc394)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x611c40, 0xc4211fe7e0, 0xc4204bc394, 0x4, 0x4, 0xc4201be800, 0x715000, 0x0)
	/usr/local/go/src/io/io.go:325 +0x58
canal/libs/github.com/siddontang/go-mysql/packet.(*Conn).ReadPacketTo(0xc42278d0c0, 0x611d00, 0xc42171fc00, 0x5, 0x0)
	/Users/liangkai/Code/gopath/src/canal/libs/github.com/siddontang/go-mysql/packet/conn.go:81 +0x89
canal/libs/github.com/siddontang/go-mysql/packet.(*Conn).ReadPacket(0xc42278d0c0, 0x0, 0x0, 0xc42003bee0, 0x2c60e4, 0xc4201d0020)
	/Users/liangkai/Code/gopath/src/canal/libs/github.com/siddontang/go-mysql/packet/conn.go:35 +0x7b
canal/libs/github.com/siddontang/go-mysql/client.(*Conn).readOK(0xc42285c070, 0xc42003bf0e, 0x0, 0x0)
	/Users/liangkai/Code/gopath/src/canal/libs/github.com/siddontang/go-mysql/client/resp.go:85 +0x5b
canal/libs/github.com/siddontang/go-mysql/client.(*Conn).Ping(0xc42285c070, 0x14, 0xc42003bf88)
	/Users/liangkai/Code/gopath/src/canal/libs/github.com/siddontang/go-mysql/client/conn.go:97 +0x7d
canal/libs/github.com/siddontang/go-mysql/replication.(*BinlogSyncer).ping(0xc4201d4880)
	/Users/liangkai/Code/gopath/src/canal/libs/github.com/siddontang/go-mysql/replication/binlogsyncer.go:250 +0x4e
created by canal/libs/github.com/siddontang/go-mysql/replication.(*BinlogSyncer).startDumpStream
	/Users/liangkai/Code/gopath/src/canal/libs/github.com/siddontang/go-mysql/replication/binlogsyncer.go:242 +0x11c

Is there something wrong?

**Comment by siddontang** [comment]
Hi @lkpjj 

We can't reuse the connection when syncing. We must use another new connection here, but if we use new, `ping` has no meaning.

**Comment by lkpjj** [comment]
can you fix this? ping method is necessary for connection without deadline.

**Comment by siddontang** [comment]
Seem not. The connection for syncing is unidirectional, only MySQL server -> sync slave. We can not send a new request with this connection to MySQL server. 

What is the problem with deadline?

**Comment by lkpjj** [comment]
mysql server will wait a period time(wait_timeout,default:28800second) before auto close this connetion id,this may cause reach the max connection of mysql server.
