### ISSUE TITLE
Flavor can suppert Percona Server?

### ISSUE THREAD

**Issue by dbaops-com** [go-mysql-org/go-mysql#464]
My Percona Server  is not work, Error:
[2020/01/25 23:47:40] [info] binlogsyncer.go:144 create BinlogSyncer with config {100 mysql 127.0.0.1 3306 mysql_user    false false <nil> false UTC false 0 0s 0s 0 false false 0}
[2020/01/25 23:47:40] [info] binlogsyncer.go:359 begin to sync binlog from position (mysql-bin.000649, 4)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5f27f7]

goroutine 1 [running]:
github.com/siddontang/go-mysql/replication.(*BinlogStreamer).GetEvent(0x0, 0x6d7740, 0xc0000f4010, 0x4, 0x0, 0x6d3460)
	/root/go/src/github.com/siddontang/go-mysql/replication/binlogstreamer.go:25 +0x37
main.main()
	/hbdata/gomysql/binlogStream.go:33 +0xd4
exit status 2

**Comment by ljluestc** [comment]
```

package main

import (
    "context"
    "fmt"
    "log"
    "os"

    "github.com/go-mysql-org/go-mysql/mysql"
    "github.com/go-mysql-org/go-mysql/replication"
)

func main() {
    // Configuration for Percona Server connection via Unix socket
    cfg := replication.BinlogSyncerConfig{
        ServerID: 100,                  // Unique server ID for replication
        Flavor:   "mysql",             // Use "mysql" for Percona Server
        Host:     "127.0.0.1",         // Host (used for protocol, but socket takes precedence)
        Port:     3306,                // Port (informational, socket overrides)
        User:     "mysql_user",        // Replace with your MySQL username
        Password: "mysql_password",    // Replace with your MySQL password
        UnixSocket: "/var/run/mysqld/mysqld.sock", // Specify Unix socket path
    }

    // Create a binlog syncer
    syncer, err := replication.NewBinlogSyncer(cfg)
    if err != nil {
        log.Fatalf("Failed to create binlog syncer: %v", err)
    }
    defer syncer.Close()

    // Specify the starting position (from your error: mysql-bin.000649, 4)
    pos := mysql.Position{
        Name: "mysql-bin.000649",
        Pos:  4,
    }

    // Start syncing from the specified position
    streamer, err := syncer.StartSync(pos)
    if err != nil {
        log.Fatalf("Failed to start sync: %v", err)
    }

    fmt.Printf("Starting to sync binlog from position %s\n", pos)

    // Context for graceful shutdown
    ctx, cancel := context.WithCancel(context.Background())
    defer cancel()

    // Stream binlog events
    for {
        select {
        case <-ctx.Done():
            fmt.Println("Shutting down binlog streamer")
            return
        default:
            ev, err := streamer.GetEvent(context.Background())
            if err != nil {
                log.Printf("Error getting event: %v", err)
                continue
            }

            // Prevent nil pointer dereference by checking the event
            if ev == nil {
                log.Println("Received nil event, skipping")
                continue
            }

            // Process the event (example: print event type and raw data)
            fmt.Printf("Event Type: %s, Raw Data: %v\n", ev.Header.EventType, ev.RawData)

            // Optionally dump the full event for debugging
            ev.Dump(os.Stdout)
        }
    }
}
```

**Comment by dveeden** [comment]
@ljluestc Is this working for you? If not, what version of go-mysql and Percona Server are you using? What error do you get?

**Comment by dveeden** [comment]
Note that we have the MariaDB and MySQL flavors and Percona Server should work with the MySQL flavor as it is a compatible fork.

Please reopen or create a new issue if I missed anything
