### ISSUE TITLE
Panic in LengthEncodedString

### ISSUE THREAD

**Issue by viciious** [go-mysql-org/go-mysql#607]
mysql version 5.7.30-33
module version: 1.3.0

```
Aug 10 13:56:45 bo15.i kvmapsrv[197265]: panic: runtime error: slice bounds out of range [:1] with capacity 0
Aug 10 13:56:45 bo15.i kvmapsrv[197265]: goroutine 1 [running]:
Aug 10 13:56:45 bo15.i kvmapsrv[197265]: github.com/go-mysql-org/go-mysql/mysql.LengthEncodedString(0xc00000a7dd, 0x0, 0x0, 0x40, 0xa0d0ec2, 0x0, 0x0, 0xa, 0x0, 0x0)
Aug 10 13:56:45 bo15.i kvmapsrv[197265]: /builds/YoUB4Gxr/1/go/ci/1763115/home/rpm/BUILD/go-299877a/_vendor/pkg/mod/github.com/go-mysql-org/go-mysql@v1.3.0/mysql/util.go:198 +0x17a
Aug 10 13:56:45 bo15.i kvmapsrv[197265]: github.com/go-mysql-org/go-mysql/mysql.RowData.ParseText(0xc00000a7dd, 0x23, 0x23, 0xc000033320, 0x5, 0x5, 0x0, 0x4, 0x0, 0xc0003fc640, ...)
Aug 10 13:56:45 bo15.i kvmapsrv[197265]: /builds/YoUB4Gxr/1/go/ci/1763115/home/rpm/BUILD/go-299877a/_vendor/pkg/mod/github.com/go-mysql-org/go-mysql@v1.3.0/mysql/rowdata.go:33 +0x1fd
Aug 10 13:56:45 bo15.i kvmapsrv[197265]: github.com/go-mysql-org/go-mysql/mysql.RowData.Parse(0xc00000a7dd, 0x23, 0x23, 0xc000033320, 0x5, 0x5, 0x200, 0x0, 0x0, 0x0, ...)
Aug 10 13:56:45 bo15.i kvmapsrv[197265]: /builds/YoUB4Gxr/1/go/ci/1763115/home/rpm/BUILD/go-299877a/_vendor/pkg/mod/github.com/go-mysql-org/go-mysql@v1.3.0/mysql/rowdata.go:16 +0x16e
Aug 10 13:56:45 bo15.i kvmapsrv[197265]: github.com/go-mysql-org/go-mysql/client.(*Conn).readResultRows(0xc00035ca00, 0xc0001f2460, 0x0, 0x0, 0xc00003ab00)
Aug 10 13:56:45 bo15.i kvmapsrv[197265]: /builds/YoUB4Gxr/1/go/ci/1763115/home/rpm/BUILD/go-299877a/_vendor/pkg/mod/github.com/go-mysql-org/go-mysql@v1.3.0/client/resp.go:399 +0x39c
Aug 10 13:56:45 bo15.i kvmapsrv[197265]: github.com/go-mysql-org/go-mysql/client.(*Conn).readResultset(0xc00035ca00, 0xc00003ab40, 0x1, 0x15, 0xc00003ab00, 0x1, 0x15, 0x0)
```

Unfortunately I can't provide more details at the moment. Hopefully I'll be able to get back to you with more details.

**Comment by viciious** [comment]
Looking at the code, it seems that line 145 of https://github.com/go-mysql-org/go-mysql/blob/v1.3.0/mysql/util.go#L145 should read as:
```
return 0, true, 0
```
instead of 
```
return 0, true, 1
```
