### ISSUE TITLE
当添加无符号列后， 提示数组越界

### ISSUE THREAD

**Issue by 892294101** [go-mysql-org/go-mysql#713]
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
myGithubLib/dds/ddscanal.(*RowsEvent).handleUnsigned(0xc0002a2280)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/rows.go:56 +0x5c5
myGithubLib/dds/ddscanal.newRowsEvent(0xc0002c8300, 0x5e4bc9, 0x6, 0xc0002385a0, 0x1, 0x2, 0xc000241080, 0x0)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/rows.go:39 +0xa8
myGithubLib/dds/ddscanal.(*Canal).handleRowsEvent(0xc0000c4000, 0xc000238600, 0x10, 0xc000025df1)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/sync.go:339 +0x15e
myGithubLib/dds/ddscanal.(*Canal).runSyncBinlog(0xc0000c4000, 0x0, 0x0)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/sync.go:116 +0x16a7
myGithubLib/dds/ddscanal.(*Canal).run(0xc0000c4000, 0x0, 0x0)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/canal.go:229 +0xe5
myGithubLib/dds/ddscanal.(*Canal).Run(...)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/canal.go:184
myGithubLib/dds/ddscanal.(*Canal).RunFrom(0xc0000c4000, 0xc0000197a0, 0x10, 0x25d3e, 0x1, 0xc0000197a0)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/canal.go:191 +0x65
main.main()
	D:/workspace/gowork/src/myGithubLib/dds/test/mysqltest.go:233 +0x3c5

**Comment by 892294101** [comment]
root@localhost [admin]> insert into testunint values(11,11,11);
Query OK, 1 row affected (0.03 sec)

root@localhost [admin]> insert into testunint(name,id) values(22,22);
Query OK, 1 row affected (0.03 sec)

root@localhost [admin]> ALTER TABLE `admin`.`testunint`  ADD COLUMN `b` int(10) unsigned NULL AFTER `a`;
Query OK, 0 rows affected (0.19 sec)
Records: 0  Duplicates: 0  Warnings: 0

root@localhost [admin]> insert into testunint(name,id,b) values(33,33,11);
Query OK, 1 row affected (0.03 sec)




2022-07-13 01:14:42.54 I NewBinlogSyncer 155 [M] create BinlogSyncer with config {1768 mysql 10.130.41.234 3306 admin   utf8 false false <nil> false UTC true 0 1s 0s 3 false false 0 <nil> 0xc000235260}
2022-07-13 01:14:42.59 I tryDump 198 [M] skip dump, use last binlog replication pos (mysql-bin.000002, 156081) or GTID set <nil>
2022-07-13 01:14:42.59 I StartSync 391 [M] begin to sync binlog from position (mysql-bin.000002, 156081)
2022-07-13 01:14:42.71 I startSyncer 36 [M] start sync binlog at binlog file (mysql-bin.000002, 156081)
2022-07-13 01:14:42.72 I parseEvent 807 [M] rotate to (mysql-bin.000002, 156081)
2022-07-13 01:14:42.72 I runSyncBinlog 79 [M] received fake rotate event, next log name is mysql-bin.000002
RAW SQL: --------------:  BEGIN
r.Rows: [[11 11 11]]Header: 1657673636 44 156311 0 1002
OnRow: Table.Schema: admin Table.Name: testunint
OnRow: Table.PKColumns: [1]
OnRow: Table.UnsignedColumns: [2]
OnRow: Table.Indexes:0 &{PRIMARY [id] [3] 0}
OnRow: Table.Indexes: [0xc00029a280]
OnRow: Table.Columns:  0   {name 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  1   {id 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  2   {a 1  int(10) unsigned false true false false [] [] 0 0}
-----------------------------------------------------------------------
action: insert
column number: 0 Data: 11
column number: 1 Data: 11
column number: 2 Data: 11
-----------------------------------------------------------------------
=======================================
OnPosSynced: m.Name:mysql-bin.000002 m.Pos:156338 





RAW SQL: --------------:  BEGIN
r.Rows: [[22 22 <nil>]]Header: 1657673655 40 156564 0 1002
OnRow: Table.Schema: admin Table.Name: testunint
OnRow: Table.PKColumns: [1]
OnRow: Table.UnsignedColumns: [2]
OnRow: Table.Indexes:0 &{PRIMARY [id] [3] 0}
OnRow: Table.Indexes: [0xc00029a280]
OnRow: Table.Columns:  0   {name 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  1   {id 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  2   {a 1  int(10) unsigned false true false false [] [] 0 0}
-----------------------------------------------------------------------
action: insert
column number: 0 Data: 22
column number: 1 Data: 22
column number: 2 Data: <nil>
-----------------------------------------------------------------------
=======================================
OnPosSynced: m.Name:mysql-bin.000002 m.Pos:156591 
RAW SQL: --------------:  ALTER TABLE `admin`.`testunint`  ADD COLUMN `b` int(10) unsigned NULL AFTER `a`
2022-07-13 01:16:17.35 I updateTable 302 [M] table structure changed, clear table cache: admin.testunint

OnTableDDL:  ALTER TABLE `admin`.`testunint`  ADD COLUMN `b` int(10) unsigned NULL AFTER `a`
=======================================
OnPosSynced: m.Name:mysql-bin.000002 m.Pos:156808 
RAW SQL: --------------:  BEGIN
r.Rows: [[33 33 <nil> 11]]r.Rows: [[33 33 <nil> 11]]Header: 1657673738 44 157039 0 1002
OnRow: Table.Schema: admin Table.Name: testunint
OnRow: Table.PKColumns: [1]
OnRow: Table.UnsignedColumns: [2 3]
OnRow: Table.Indexes:0 &{PRIMARY [id] [4] 0}
OnRow: Table.Indexes: [0xc00009e8c0]
OnRow: Table.Columns:  0   {name 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  1   {id 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  2   {a 1  int(10) unsigned false true false false [] [] 0 0}
OnRow: Table.Columns:  3   {b 1  int(10) unsigned false true false false [] [] 0 0}
-----------------------------------------------------------------------
action: insert
column number: 0 Data: 33
column number: 1 Data: 33
column number: 2 Data: <nil>
column number: 3 Data: 11
-----------------------------------------------------------------------
=======================================
OnPosSynced: m.Name:mysql-bin.000002 m.Pos:157066 

==============================================================================================================================
如果这时我关闭canal后，重新启动canal
2022-07-13 01:17:34.95 I NewBinlogSyncer 155 [M] create BinlogSyncer with config {1612 mysql 10.130.41.234 3306 admin   utf8 false false <nil> false UTC true 0 1s 0s 3 false false 0 <nil> 0xc000090150}
2022-07-13 01:17:34.99 I tryDump 198 [M] skip dump, use last binlog replication pos (mysql-bin.000002, 156081) or GTID set <nil>
2022-07-13 01:17:34.99 I StartSync 391 [M] begin to sync binlog from position (mysql-bin.000002, 156081)
2022-07-13 01:17:35.14 I startSyncer 36 [M] start sync binlog at binlog file (mysql-bin.000002, 156081)
2022-07-13 01:17:35.15 I parseEvent 807 [M] rotate to (mysql-bin.000002, 156081)
2022-07-13 01:17:35.15 I runSyncBinlog 79 [M] received fake rotate event, next log name is mysql-bin.000002
RAW SQL: --------------:  BEGIN
r.Rows: [[11 11 11]]r.Rows: [[11 11 11]]panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
myGithubLib/dds/ddscanal.(*RowsEvent).handleUnsigned(0xc0002d2140)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/rows.go:57 +0x64d
myGithubLib/dds/ddscanal.newRowsEvent(0xc000290300, 0x13b4bc9, 0x6, 0xc00004a5f0, 0x1, 0x3, 0xc000240480, 0x0)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/rows.go:39 +0xa8
myGithubLib/dds/ddscanal.(*Canal).handleRowsEvent(0xc0000c4000, 0xc0002383f0, 0x10, 0xc0000261b1)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/sync.go:339 +0x15e
myGithubLib/dds/ddscanal.(*Canal).runSyncBinlog(0xc0000c4000, 0x0, 0x0)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/sync.go:116 +0x16a7
myGithubLib/dds/ddscanal.(*Canal).run(0xc0000c4000, 0x0, 0x0)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/canal.go:229 +0xe5
myGithubLib/dds/ddscanal.(*Canal).Run(...)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/canal.go:184
myGithubLib/dds/ddscanal.(*Canal).RunFrom(0xc0000c4000, 0xc000282050, 0x10, 0x261b1, 0x1, 0xc000282050)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/canal.go:191 +0x65
main.main()
	D:/workspace/gowork/src/myGithubLib/dds/test/mysqltest.go:233 +0x3c5

**Comment by 892294101** [comment]
“root@localhost [admin]> insert into testunint values(11,11,11);
Query OK, 1 row affected (0.03 sec)

root@localhost [admin]> insert into testunint(name,id) values(22,22);
Query OK, 1 row affected (0.03 sec)

root@localhost [admin]> ALTER TABLE `admin`.`testunint`  ADD COLUMN `b` int(10) unsigned NULL AFTER `a`;
Query OK, 0 rows affected (0.19 sec)
Records: 0  Duplicates: 0  Warnings: 0

root@localhost [admin]> insert into testunint(name,id,b) values(33,33,11);
Query OK, 1 row affected (0.03 sec)




2022-07-13 01:14:42.54 I NewBinlogSyncer 155 [M] create BinlogSyncer with config {1768 mysql 10.130.41.234 3306 admin   utf8 false false <nil> false UTC true 0 1s 0s 3 false false 0 <nil> 0xc000235260}
2022-07-13 01:14:42.59 I tryDump 198 [M] skip dump, use last binlog replication pos (mysql-bin.000002, 156081) or GTID set <nil>
2022-07-13 01:14:42.59 I StartSync 391 [M] begin to sync binlog from position (mysql-bin.000002, 156081)
2022-07-13 01:14:42.71 I startSyncer 36 [M] start sync binlog at binlog file (mysql-bin.000002, 156081)
2022-07-13 01:14:42.72 I parseEvent 807 [M] rotate to (mysql-bin.000002, 156081)
2022-07-13 01:14:42.72 I runSyncBinlog 79 [M] received fake rotate event, next log name is mysql-bin.000002
RAW SQL: --------------:  BEGIN
r.Rows: [[11 11 11]]Header: 1657673636 44 156311 0 1002
OnRow: Table.Schema: admin Table.Name: testunint
OnRow: Table.PKColumns: [1]
OnRow: Table.UnsignedColumns: [2]
OnRow: Table.Indexes:0 &{PRIMARY [id] [3] 0}
OnRow: Table.Indexes: [0xc00029a280]
OnRow: Table.Columns:  0   {name 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  1   {id 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  2   {a 1  int(10) unsigned false true false false [] [] 0 0}
-----------------------------------------------------------------------
action: insert
column number: 0 Data: 11
column number: 1 Data: 11
column number: 2 Data: 11
-----------------------------------------------------------------------
=======================================
OnPosSynced: m.Name:mysql-bin.000002 m.Pos:156338 





RAW SQL: --------------:  BEGIN
r.Rows: [[22 22 <nil>]]Header: 1657673655 40 156564 0 1002
OnRow: Table.Schema: admin Table.Name: testunint
OnRow: Table.PKColumns: [1]
OnRow: Table.UnsignedColumns: [2]
OnRow: Table.Indexes:0 &{PRIMARY [id] [3] 0}
OnRow: Table.Indexes: [0xc00029a280]
OnRow: Table.Columns:  0   {name 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  1   {id 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  2   {a 1  int(10) unsigned false true false false [] [] 0 0}
-----------------------------------------------------------------------
action: insert
column number: 0 Data: 22
column number: 1 Data: 22
column number: 2 Data: <nil>
-----------------------------------------------------------------------
=======================================
OnPosSynced: m.Name:mysql-bin.000002 m.Pos:156591 
RAW SQL: --------------:  ALTER TABLE `admin`.`testunint`  ADD COLUMN `b` int(10) unsigned NULL AFTER `a`
2022-07-13 01:16:17.35 I updateTable 302 [M] table structure changed, clear table cache: admin.testunint

OnTableDDL:  ALTER TABLE `admin`.`testunint`  ADD COLUMN `b` int(10) unsigned NULL AFTER `a`
=======================================
OnPosSynced: m.Name:mysql-bin.000002 m.Pos:156808 
RAW SQL: --------------:  BEGIN
r.Rows: [[33 33 <nil> 11]]r.Rows: [[33 33 <nil> 11]]Header: 1657673738 44 157039 0 1002
OnRow: Table.Schema: admin Table.Name: testunint
OnRow: Table.PKColumns: [1]
OnRow: Table.UnsignedColumns: [2 3]
OnRow: Table.Indexes:0 &{PRIMARY [id] [4] 0}
OnRow: Table.Indexes: [0xc00009e8c0]
OnRow: Table.Columns:  0   {name 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  1   {id 1  int(11) false false false false [] [] 0 0}
OnRow: Table.Columns:  2   {a 1  int(10) unsigned false true false false [] [] 0 0}
OnRow: Table.Columns:  3   {b 1  int(10) unsigned false true false false [] [] 0 0}
-----------------------------------------------------------------------
action: insert
column number: 0 Data: 33
column number: 1 Data: 33
column number: 2 Data: <nil>
column number: 3 Data: 11
-----------------------------------------------------------------------
=======================================
OnPosSynced: m.Name:mysql-bin.000002 m.Pos:157066 

==============================================================================================================================
如果这时我关闭canal后，重新启动canal
2022-07-13 01:17:34.95 I NewBinlogSyncer 155 [M] create BinlogSyncer with config {1612 mysql 10.130.41.234 3306 admin   utf8 false false <nil> false UTC true 0 1s 0s 3 false false 0 <nil> 0xc000090150}
2022-07-13 01:17:34.99 I tryDump 198 [M] skip dump, use last binlog replication pos (mysql-bin.000002, 156081) or GTID set <nil>
2022-07-13 01:17:34.99 I StartSync 391 [M] begin to sync binlog from position (mysql-bin.000002, 156081)
2022-07-13 01:17:35.14 I startSyncer 36 [M] start sync binlog at binlog file (mysql-bin.000002, 156081)
2022-07-13 01:17:35.15 I parseEvent 807 [M] rotate to (mysql-bin.000002, 156081)
2022-07-13 01:17:35.15 I runSyncBinlog 79 [M] received fake rotate event, next log name is mysql-bin.000002
RAW SQL: --------------:  BEGIN
r.Rows: [[11 11 11]]r.Rows: [[11 11 11]]panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
myGithubLib/dds/ddscanal.(*RowsEvent).handleUnsigned(0xc0002d2140)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/rows.go:57 +0x64d
myGithubLib/dds/ddscanal.newRowsEvent(0xc000290300, 0x13b4bc9, 0x6, 0xc00004a5f0, 0x1, 0x3, 0xc000240480, 0x0)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/rows.go:39 +0xa8
myGithubLib/dds/ddscanal.(*Canal).handleRowsEvent(0xc0000c4000, 0xc0002383f0, 0x10, 0xc0000261b1)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/sync.go:339 +0x15e
myGithubLib/dds/ddscanal.(*Canal).runSyncBinlog(0xc0000c4000, 0x0, 0x0)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/sync.go:116 +0x16a7
myGithubLib/dds/ddscanal.(*Canal).run(0xc0000c4000, 0x0, 0x0)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/canal.go:229 +0xe5
myGithubLib/dds/ddscanal.(*Canal).Run(...)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/canal.go:184
myGithubLib/dds/ddscanal.(*Canal).RunFrom(0xc0000c4000, 0xc000282050, 0x10, 0x261b1, 0x1, 0xc000282050)
	D:/workspace/gowork/src/myGithubLib/dds/ddscanal/canal.go:191 +0x65
main.main()
	D:/workspace/gowork/src/myGithubLib/dds/test/mysqltest.go:233 +0x3c5


”

**Comment by libinreal** [comment]
最根本的原因就是，binlog读取到的row 结构和table 实时的结构不一致了，添加或删除了字段之后，就会报这个错，简单在vendor目录的 `github.com/siddontang/go-mysql/canal/rows.go:56` 前面添加一越界判断:
`if columnIdx >= len(r.Rows[i]) {
			continue
		}
		switch value := r.Rows[i][columnIdx].(type) {`

**Comment by guihouchang** [comment]
这个没人提个PR修复下吗
